version: '3.4'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'

  nominatim:
      container_name: nominatim
      image: mediagis/nominatim:4.2
      restart: always
      ports:
          - "8080:8080"
      environment:
          # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
          PBF_URL: https://download.geofabrik.de/europe/romania-latest.osm.pbf
          REPLICATION_URL: https://download.geofabrik.de/europe/romania-updates/
      volumes:
          - nominatim-data:/var/lib/postgresql/14/main
      shm_size: 1gb

  migrator:
    build:
      context: .
      dockerfile: src/PollingStationsResolver.Migrator/Dockerfile
    environment:
      ConnectionStrings__PollingStationsResolverApi: ${DB_CONNECTION_STRING}
    depends_on:
      - postgres

  resolverapi:
    build:
      context: .
      dockerfile: src/PollingStationsResolver.Api/Dockerfile
    environment:
      ConnectionStrings__PollingStationsResolverApi: ${DB_CONNECTION_STRING}
      ConnectionStrings__HangfireConnection: ${HANGFIRE_DB_CONNECTION_STRING}
      Token__SigningKey: ${TOKEN_SIGNING_KEY}
      AdminCredentials__Username: ${ADMIN_USERNAME}
      AdminCredentials__Password: ${ADMIN_PASSWORD}
      Geocoding__Nominatim__BaseUrl: http://nominatim:8080
      Geocoding__HereMaps__BaseUrl: https://geocode.search.hereapi.com
      Geocoding__HereMaps__ApiKey: ${HEREMAPS_APIKEY}
    depends_on:
      - postgres
      - migrator
      - nominatim

volumes:
    nominatim-data: